# Generated by Django 3.2.25 on 2026-08-14 11:12
#
# LOCAL MIGRATION — not from upstream. Widens TextAnnotation.kind from
# varchar(7) to varchar(11) so it can hold "syntax-tree". Django 3.2's
# fields.E009 check refuses to start without this. SQLite never enforced the
# length, so the defect was invisible on this deployment; on Postgres it
# would have rejected every syntax-tree annotation.
#
# If upstream ever adds its own 0007, this file has to be renumbered.
# See packages/README.md.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaife_viewer_atlas', '0006_dictionary_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textannotation',
            name='kind',
            field=models.CharField(choices=[('scholia', 'Scholia'), ('syntax-tree', 'Syntax tree')], default='scholia', max_length=11),
        ),
    ]
